name = "quran"
main = "src/worker.js"
compatibility_date = "2024-05-11"
workers_dev = true

[placement]
mode = "smart"

[vars]
QURL='https://quran-81e.pages.dev/quran.json'

[env.local.vars]
QURL='http://localhost/quran.json'
