name = "quran"
main = "src/worker.js"
compatibility_date = "2024-05-11"
workers_dev = true

[[routes]]
pattern = "quran.networkreverse.com/*"
zone_name = "networkreverse.com"

[placement]
mode = "smart"

[vars]
QURL='https://quran-81e.pages.dev/quran.json'

[env.local.vars]
QURL='https://squid.sa.ya/quran.json'
